// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace testtest.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20230628161123_Lophoc")]
    partial class Lophoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("testtest.Models.Lophoc", b =>
                {
                    b.Property<string>("Malop")
                        .HasColumnType("TEXT");

                    b.Property<string>("Siso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenlop")
                        .IsRequired()
                        .HasColumnType("TEXT");
                     b.Property<string>("solop")
                        .IsRequired()
                        .HasColumnType("TEXT");


                    b.HasKey("Malop");

                    b.ToTable("Lophoc");
                });
#pragma warning restore 612, 618
        }
    }
}
